server:
   port: 8761
spring:
   application:
      name: registry
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
         defaultZone: http://106.12.204.95:${server.port}/eureka/