server:
   port: 8761
spring:
   application:
      name: registry
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
         defaultZone: http://192.168.1.11:${server.port}/eureka/